### ISSUE TITLE
Incorrect parameter for ds/random-split

### ISSUE THREAD

**Issue by chamaeleon** [kimim/clj-djl-examples#2]
mushrooms.clj has the code
```
(let [[mushroom-train mushroom-test] (ds/random-split dataset [70 30])
  ...)
```
However, `ds/random-split` is currently defined as
```
(defn random-split
  [dataset & ratios]
  (.randomSplit dataset (int-array ratios)))
```
which means ratios becomes a list containing one element, the array `[70 30]`, instead of a list containing `70` and `30`. Either the mushrooms.clj code need to be updated to be
```
(let [[mushroom-train mushroom-test] (ds/random-split dataset 70 30)
  ...)
```
or the ampersand needs to be removed from the random-split definition.

I would assume the former (changing the call in mushrooms.clj) is preferable since it is an example, and not an API function that may be in use by other people.

**Comment by kimim** [comment]
Yes, I was thinking using vector is more clojure-style, but at last plain number list style is decided.
